### ISSUE TITLE
Issue Title: Error Computing String Metric in Column - Value Type Error

### ISSUE THREAD

**Issue by youen** [CGI-FR/RIMO#11]
**Issue Description:**
When processing the provided JSON input data, the Rimo tool encounters an error that leads to the program's failure. The error message indicates an issue with computing a string metric in the "PRENOM" column, resulting in a value type error. This error seems to be related to the data type or content within the "PRENOM" column.

**Error Details:**
```
1:41PM INF rimo v0.1.0 (commit=391e8980ca365942c6b30e3993a73902eade156a date=2023-08-23 by=youen)
2023/08/23 13:41:56 failed to compute metric: error computing string metric in column PRENOM : value type error : expected numeric found <nil>: <nil>
```

**Steps to Reproduce:**
1. Use the provided JSON input data: 
   ```json
   {"EMAIL":"anomnym@linopimo.fr","GROUPE_ID":3,"ID":61,"ID_TYPE_UTILISATEUR":null,"LOGIN":"*****","MDP":"******","NOM":"***","PRENOM":null,"PROFIL_ID":2}
   ```
2. Run the Rimo tool with the data.

**Expected Behavior:**
The Rimo tool should be able to process the input data without encountering a value type error in the "PRENOM" column. The program should successfully compute the relevant metrics and perform the necessary operations without failures.

**Actual Behavior:**
The tool encounters a value type error in the "PRENOM" column, leading to the program's failure. This issue prevents the program from completing its execution successfully.

**Additional Context:**
- Rimo version: [Specify Rimo version here]
- Operating System: [Specify your operating system here]
- This issue seems to be related to a specific column ("PRENOM") within the input data. The column might contain null values or other data that is causing the type error during metric computation.

**Comment by mathisdrn** [comment]
Fixed in refactor MR.
